{
  "openapi": "3.0.0",
  "info": {
    "title": "Nakatomi Inc. api",
    "version": "0.0.0"
  },
  "tags": [
    {
      "name": "Customer"
    },
    {
      "name": "Order"
    },
    {
      "name": "Product"
    },
    {
      "name": "Payment"
    }
  ],
  "paths": {
    "/customers": {
      "get": {
        "operationId": "Customers_list",
        "parameters": [
          {
            "name": "search",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string",
              "x-filter-by": ["firstName", "lastName", "email"]
            },
            "x-filter-by": ["firstName", "lastName", "email"],
            "explode": false
          }
        ],
        "responses": {
          "200": {
            "description": "The request has succeeded.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CustomersResponse"
                }
              }
            }
          }
        },
        "tags": ["Customer"],
        "x-icon": "Users2",
        "x-description": "View and manage your customers",
        "x-label": "Customers"
      }
    },
    "/orders": {
      "get": {
        "operationId": "Orders_list",
        "parameters": [],
        "responses": {
          "200": {
            "description": "The request has succeeded.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OrdersResponse"
                }
              }
            }
          }
        },
        "tags": ["Order"],
        "x-icon": "ShoppingCart",
        "x-description": "View and manage your orders",
        "x-label": "Orders"
      },
      "post": {
        "operationId": "Orders_create",
        "parameters": [],
        "responses": {
          "200": {
            "description": "The request has succeeded.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Order"
                }
              }
            }
          }
        },
        "tags": ["Order"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrder"
              }
            }
          }
        },
        "x-description": "Manually create a new order with optional delivery address",
        "x-label": "Create order"
      }
    },
    "/payments": {
      "get": {
        "operationId": "Payments_list",
        "parameters": [],
        "responses": {
          "200": {
            "description": "The request has succeeded.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PaymentsResponse"
                }
              }
            }
          }
        },
        "tags": ["Payment"],
        "x-icon": "Banknote",
        "x-description": "View and manage your payments",
        "x-label": "Payments"
      }
    },
    "/products": {
      "get": {
        "operationId": "Products_list",
        "parameters": [
          {
            "name": "search",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "x-filter-by": ["name", "description"]
            },
            "x-filter-by": ["name", "description"],
            "explode": false
          }
        ],
        "responses": {
          "200": {
            "description": "The request has succeeded.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductsResponse"
                }
              }
            }
          }
        },
        "tags": ["Product"],
        "x-icon": "Package",
        "x-description": "View and manage your products",
        "x-label": "Products"
      },
      "post": {
        "operationId": "Products_create",
        "parameters": [],
        "responses": {
          "200": {
            "description": "The request has succeeded.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Product"
                }
              }
            }
          }
        },
        "tags": ["Product"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateProduct"
              }
            }
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "operationId": "Products_get",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The request has succeeded.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Product"
                }
              }
            }
          }
        },
        "tags": ["Product"]
      }
    }
  },
  "components": {
    "schemas": {
      "Address": {
        "type": "object",
        "required": ["line1", "line2", "city", "state", "zip", "country"],
        "properties": {
          "line1": {
            "type": "string",
            "x-label": "Line 1"
          },
          "line2": {
            "type": "string",
            "x-label": "Line 2"
          },
          "city": {
            "type": "string",
            "x-label": "City"
          },
          "state": {
            "type": "string",
            "x-label": "State"
          },
          "zip": {
            "type": "string",
            "x-label": "Zip"
          },
          "country": {
            "$ref": "#/components/schemas/CountryCode"
          }
        }
      },
      "CountryCode": {
        "type": "string",
        "enum": ["de", "fr", "it", "es", "uk", "us", "ca", "au", "jp"],
        "x-label": "Country"
      },
      "CreateOrder": {
        "type": "object",
        "required": ["customerId", "items"],
        "properties": {
          "customerId": {
            "type": "string",
            "x-references": "Customer",
            "x-label": "Customer"
          },
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/OrderItem"
            },
            "x-label": "Items"
          },
          "deliveryAddress": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Address"
              }
            ],
            "x-label": "Delivery address"
          }
        }
      },
      "CreateProduct": {
        "type": "object",
        "required": ["name", "price"],
        "properties": {
          "name": {
            "type": "string",
            "x-label": "Name"
          },
          "price": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Money"
              }
            ],
            "x-label": "Price"
          },
          "description": {
            "type": "string",
            "x-label": "Description"
          }
        }
      },
      "Currency": {
        "type": "string",
        "enum": ["USD", "EUR", "GBP"],
        "x-label": "Currency"
      },
      "Customer": {
        "type": "object",
        "required": ["id", "firstName", "lastName", "email", "createdAt"],
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid",
            "x-label": "Id"
          },
          "firstName": {
            "type": "string",
            "x-label": "First name"
          },
          "lastName": {
            "type": "string",
            "x-label": "Last name"
          },
          "email": {
            "type": "string",
            "format": "email",
            "x-label": "Email"
          },
          "lastOrderDate": {
            "type": "string",
            "format": "date",
            "x-label": "Last order date"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "x-label": "Created at"
          }
        }
      },
      "CustomersResponse": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Customer"
        },
        "example": [
          {
            "id": "0192cf25-6f22-7056-9c73-fd15af81b81f",
            "firstName": "John",
            "lastName": "Doe",
            "email": "john.doe@example.com",
            "createdAt": "2024-01-01T00:00:00Z"
          },
          {
            "id": "0192cf25-9630-7f1e-9e5f-d5f5ad343e95",
            "firstName": "Jane",
            "lastName": "Doe",
            "email": "jane.doe@example.com",
            "lastOrderDate": "2023-05-08T00:00:00Z",
            "createdAt": "2023-02-07T00:00:00Z"
          },
          {
            "id": "0192cf25-aea7-72ba-9aae-91c0c043052a",
            "firstName": "John",
            "lastName": "Smith",
            "email": "john.smith@example.com",
            "createdAt": "2023-11-21T00:00:00Z"
          },
          {
            "id": "0192cf25-c90a-7989-89d2-a26799d5babd",
            "firstName": "Jane",
            "lastName": "Smith",
            "email": "jane.smith@example.com",
            "lastOrderDate": "2023-09-21T00:00:00Z",
            "createdAt": "2023-08-30T00:00:00Z"
          },
          {
            "id": "0192cf25-e1e2-7003-bcdb-678cdfe50c25",
            "firstName": "Charlie",
            "lastName": "Doe",
            "email": "charlie.doe@example.com",
            "createdAt": "2023-07-15T00:00:00Z"
          },
          {
            "id": "0192cf25-f7c3-7fa4-9cd7-e409ef27110b",
            "firstName": "Rose",
            "lastName": "Simmons",
            "email": "rose.simmons@example.com",
            "lastOrderDate": "2023-06-01T00:00:00Z",
            "createdAt": "2023-05-10T00:00:00Z"
          }
        ]
      },
      "Money": {
        "type": "object",
        "required": ["value", "currency"],
        "properties": {
          "value": {
            "type": "number",
            "format": "double"
          },
          "currency": {
            "$ref": "#/components/schemas/Currency"
          }
        }
      },
      "Order": {
        "type": "object",
        "required": ["id", "status", "customer", "items", "total", "createdAt"],
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid",
            "x-label": "Id"
          },
          "status": {
            "$ref": "#/components/schemas/OrderStatus"
          },
          "customer": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Customer"
              }
            ],
            "x-label": "Customer"
          },
          "deliveryAddress": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Address"
              }
            ],
            "x-label": "Delivery address"
          },
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/OrderItem"
            },
            "x-label": "Items"
          },
          "total": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Money"
              }
            ],
            "x-label": "Order total"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "x-label": "Created at"
          }
        }
      },
      "OrderItem": {
        "type": "object",
        "required": ["productId", "quantity"],
        "properties": {
          "productId": {
            "type": "string",
            "format": "uuid",
            "x-references": "Product",
            "x-label": "Product"
          },
          "quantity": {
            "type": "integer",
            "x-label": "Quantity"
          }
        }
      },
      "OrderStatus": {
        "type": "string",
        "enum": ["Received", "Processing", "Shipped", "Delivered", "Cancelled", "Returned"],
        "x-label": "Status"
      },
      "OrdersResponse": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Order"
        },
        "example": [
          {
            "id": "0192cf02-4a5c-76cb-abb2-1852afeb1c3b",
            "status": "Received",
            "customer": {
              "id": "1",
              "firstName": "John",
              "lastName": "Doe",
              "email": "john.doe@example.com",
              "createdAt": "2024-01-01T00:00:00Z"
            },
            "deliveryAddress": {
              "line1": "123 Main St",
              "line2": "Apt 4B",
              "city": "New York",
              "state": "NY",
              "zip": "10001",
              "country": "us"
            },
            "items": [
              {
                "productId": "0192cf12-752a-77af-9947-5546e258bc56",
                "quantity": 2
              },
              {
                "productId": "0192cf12-a50b-7e70-95fa-d7a383cf1c5d",
                "quantity": 7
              },
              {
                "productId": "0192cf12-c305-7baf-8d07-490c7539a367",
                "quantity": 5
              }
            ],
            "total": {
              "value": 200,
              "currency": "USD"
            },
            "createdAt": "2024-01-01T00:00:00Z"
          },
          {
            "id": "0192cf10-85dc-7d46-bd43-da3847d88b59",
            "status": "Processing",
            "customer": {
              "id": "2",
              "firstName": "Jane",
              "lastName": "Doe",
              "email": "jane.doe@example.com",
              "createdAt": "2024-01-01T00:00:00Z"
            },
            "deliveryAddress": {
              "line1": "456 Elm St",
              "line2": "Apt 5C",
              "city": "Los Angeles",
              "state": "CA",
              "zip": "90001",
              "country": "us"
            },
            "items": [
              {
                "productId": "0192cf12-de49-7b16-8abd-3db644655ca3",
                "quantity": 1
              },
              {
                "productId": "0192cf13-14d7-71e3-9266-f62691c456ec",
                "quantity": 1
              }
            ],
            "total": {
              "value": 150.75,
              "currency": "USD"
            },
            "createdAt": "2024-01-01T00:00:00Z"
          }
        ]
      },
      "Payment": {
        "type": "object",
        "required": ["id", "amount", "status", "createdAt"],
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid",
            "x-label": "Id"
          },
          "amount": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Money"
              }
            ],
            "x-label": "Amount"
          },
          "status": {
            "$ref": "#/components/schemas/PaymentStatus"
          },
          "email": {
            "type": "string",
            "format": "email",
            "x-label": "Email"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "x-label": "Created at"
          }
        }
      },
      "PaymentStatus": {
        "type": "string",
        "enum": ["Pending", "Completed", "Failed"],
        "x-label": "Status"
      },
      "PaymentsResponse": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Payment"
        },
        "example": [
          {
            "id": "0192cf24-ad68-784d-9b75-fba6383194e8",
            "amount": {
              "value": 100,
              "currency": "USD"
            },
            "status": "Pending",
            "email": "user1@example.com",
            "createdAt": "2024-01-01T00:00:00Z"
          },
          {
            "id": "0192cf24-c944-76e8-9b77-cd2fe5263023",
            "amount": {
              "value": 200,
              "currency": "EUR"
            },
            "status": "Completed",
            "email": "user2@example.com",
            "createdAt": "2024-01-02T00:00:00Z"
          },
          {
            "id": "0192cf24-e056-7616-bb14-70d835f52e11",
            "amount": {
              "value": 150,
              "currency": "GBP"
            },
            "status": "Failed",
            "email": "user3@example.com",
            "createdAt": "2024-01-03T00:00:00Z"
          },
          {
            "id": "0192cf24-fe65-7520-a607-cb728e45229c",
            "amount": {
              "value": 152,
              "currency": "USD"
            },
            "status": "Completed",
            "email": "user4@example.com",
            "createdAt": "2024-05-28T00:00:00Z"
          }
        ]
      },
      "Product": {
        "type": "object",
        "required": ["id", "name", "status", "price", "totalSales", "createdAt"],
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid",
            "x-label": "Id"
          },
          "name": {
            "type": "string",
            "x-label": "Name"
          },
          "status": {
            "$ref": "#/components/schemas/ProductStatus"
          },
          "price": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Money"
              }
            ],
            "x-label": "Price"
          },
          "totalSales": {
            "type": "integer",
            "x-label": "Total sales"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "x-label": "Created at"
          }
        }
      },
      "ProductStatus": {
        "type": "string",
        "enum": ["Active", "Draft"],
        "x-label": "Status"
      },
      "ProductsResponse": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Product"
        },
        "example": [
          {
            "id": "0192cf12-752a-77af-9947-5546e258bc56",
            "name": "Laser Lemonade Machine",
            "status": "Draft",
            "price": {
              "value": 499.99,
              "currency": "USD"
            },
            "totalSales": 25,
            "createdAt": "2020-01-01T00:00:00Z"
          },
          {
            "id": "0192cf12-a50b-7e70-95fa-d7a383cf1c5d",
            "name": "Hypernova Headphones",
            "status": "Active",
            "price": {
              "value": 129.99,
              "currency": "USD"
            },
            "totalSales": 100,
            "createdAt": "2023-10-18T03:21:00Z"
          },
          {
            "id": "0192cf12-c305-7baf-8d07-490c7539a367",
            "name": "AeroGlow Desk Lamp",
            "status": "Active",
            "price": {
              "value": 39.99,
              "currency": "USD"
            },
            "totalSales": 50,
            "createdAt": "2023-11-29T08:15:00Z"
          },
          {
            "id": "0192cf12-de49-7b16-8abd-3db644655ca3",
            "name": "TechTonic Energy Drink",
            "status": "Draft",
            "price": {
              "value": 2.99,
              "currency": "USD"
            },
            "totalSales": 0,
            "createdAt": "2023-12-25T23:59:00Z"
          },
          {
            "id": "0192cf13-14d7-71e3-9266-f62691c456ec",
            "name": "Gamer Gear Pro Controller",
            "status": "Active",
            "price": {
              "value": 58.99,
              "currency": "USD"
            },
            "totalSales": 75,
            "createdAt": "2024-01-01T00:00:00Z"
          },
          {
            "id": "0192cf13-3676-780c-a011-4dedb835d726",
            "name": "Luminous VR Headset",
            "status": "Active",
            "price": {
              "value": 199.99,
              "currency": "USD"
            },
            "totalSales": 30,
            "createdAt": "2024-02-14T02:14:00Z"
          }
        ]
      }
    }
  },
  "servers": [
    {
      "url": "https://example.com",
      "description": "Single server endpoint",
      "variables": {}
    }
  ]
}
